version: '3.9'

services:
  parking_api:
    build: .
    command: npm start
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_PORT: 27017
      DB_HOST: mongo_db
      HOST: 0.0.0.0
      DB_NAME: mlab

  mongodb:
    container_name: mongo_db
    image: mongo:4.4.11
    ports:
      - 2717:27017
    restart: always
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}
